-- Supabase migration for Market Mentor bot.
-- Run this SQL in Supabase SQL Editor or keep it as a migration file.

create table if not exists public.users (
    id bigint generated by default as identity primary key,
    telegram_id bigint not null unique,
    username text,
    first_name text,
    notification_settings jsonb not null default '{}'::jsonb,
    preferences jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.requests (
    id bigint generated by default as identity primary key,
    telegram_id bigint not null references public.users (telegram_id) on delete cascade,
    request_type text not null,
    command text not null,
    prompt text,
    created_at timestamptz not null default now()
);

create table if not exists public.history (
    id bigint generated by default as identity primary key,
    telegram_id bigint not null references public.users (telegram_id) on delete cascade,
    user_message text not null,
    bot_response text not null,
    created_at timestamptz not null default now()
);

create index if not exists idx_requests_telegram_id_created_at
    on public.requests (telegram_id, created_at desc);

create index if not exists idx_history_telegram_id_created_at
    on public.history (telegram_id, created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists trg_users_set_updated_at on public.users;

create trigger trg_users_set_updated_at
before update on public.users
for each row
execute function public.set_updated_at();
